name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-20.04
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
  
#   tag_release:
#     needs: [deployment_pipeline]
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Bump version and push tag
#         uses: anothrNick/github-tag-action@1.36.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
